spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/authportal
    username: postgres
    password: zxca
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  thymeleaf:
    cache: false

totp:
  window-size: 1
  period: 30

app:
  webauthn:
    rp-id: localhost
    rp-name: Auth Portal
    origin: http://localhost:8080

logging:
  level:
    com.svinstvo.og.portal: INFO
